// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_a117111e721ea8c6, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_a117111e721ea8c6, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 托运结果
type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_a117111e721ea8c6, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

// 查看货物信息的请求
// 客户端想要从服务端请求数据，必须有请求格式，哪怕为空
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_a117111e721ea8c6, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "proto.Consignment")
	proto.RegisterType((*Container)(nil), "proto.Container")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	// 托运一批货物
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	// 查看托运货物的信息
	GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ShippingService/CreateConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ShippingService/GetConsignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	// 托运一批货物
	CreateConsignment(context.Context, *Consignment) (*Response, error)
	// 查看托运货物的信息
	GetConsignments(context.Context, *GetRequest) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShippingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GetConsignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetConsignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShippingService/GetConsignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetConsignments(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShippingService_CreateConsignment_Handler,
		},
		{
			MethodName: "GetConsignments",
			Handler:    _ShippingService_GetConsignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consignment.proto",
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_consignment_a117111e721ea8c6) }

var fileDescriptor_consignment_a117111e721ea8c6 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x3d, 0x4e, 0xc3, 0x30,
	0x14, 0x26, 0xfd, 0xcf, 0x4b, 0x45, 0xe9, 0x1b, 0xc0, 0x82, 0x81, 0x28, 0x53, 0xa7, 0x0a, 0x15,
	0x04, 0x12, 0x6b, 0x87, 0xaa, 0xab, 0x7b, 0x00, 0x54, 0xe2, 0xa7, 0xd4, 0x12, 0xb5, 0x83, 0xed,
	0x96, 0x1b, 0x70, 0x00, 0x0e, 0xc1, 0x39, 0x51, 0x9d, 0x84, 0x1a, 0xd1, 0x29, 0xfa, 0xfe, 0xf2,
	0x7d, 0xb6, 0x61, 0x9c, 0x6b, 0x65, 0x65, 0xa1, 0xb6, 0xa4, 0xdc, 0xb4, 0x34, 0xda, 0x69, 0xec,
	0xfa, 0x4f, 0xf6, 0x1d, 0x41, 0x32, 0x3f, 0x8a, 0x78, 0x0e, 0x2d, 0x29, 0x58, 0x94, 0x46, 0x93,
	0x98, 0xb7, 0xa4, 0xc0, 0x14, 0x12, 0x41, 0x36, 0x37, 0xb2, 0x74, 0x52, 0x2b, 0xd6, 0xf2, 0x42,
	0x48, 0xe1, 0x25, 0xf4, 0x3e, 0x48, 0x16, 0x1b, 0xc7, 0xda, 0x69, 0x34, 0xe9, 0xf2, 0x1a, 0xe1,
	0x1d, 0x40, 0xae, 0x95, 0x5b, 0x4b, 0x45, 0xc6, 0xb2, 0x4e, 0xda, 0x9e, 0x24, 0xb3, 0x8b, 0xaa,
	0x7c, 0x3a, 0x6f, 0x04, 0x1e, 0x78, 0xf0, 0x06, 0xe2, 0x3d, 0x59, 0x4b, 0x6f, 0x2f, 0x52, 0xb0,
	0xae, 0x6f, 0x1a, 0x54, 0xc4, 0x52, 0x64, 0x5b, 0x88, 0x7f, 0x53, 0xff, 0x56, 0xde, 0x42, 0x92,
	0xef, 0xac, 0xd3, 0x5b, 0x32, 0x87, 0x6c, 0xb5, 0x12, 0x1a, 0x6a, 0x29, 0x0e, 0x23, 0xb5, 0x91,
	0x85, 0x54, 0x7e, 0x64, 0xcc, 0x6b, 0x84, 0x57, 0xd0, 0xdf, 0xd9, 0x2a, 0xd4, 0xa9, 0x84, 0x03,
	0x5c, 0x8a, 0xec, 0x2b, 0x82, 0x01, 0x27, 0x5b, 0x6a, 0x65, 0x09, 0x19, 0xf4, 0x73, 0x43, 0x6b,
	0x47, 0x55, 0xe7, 0x80, 0x37, 0x10, 0x1f, 0x20, 0x09, 0xae, 0xd6, 0x17, 0x27, 0x33, 0x3c, 0x9e,
	0xb2, 0x51, 0x78, 0x68, 0xc3, 0x47, 0x18, 0x06, 0xd0, 0xb2, 0xb6, 0xbf, 0x9c, 0x53, 0xb1, 0x3f,
	0xbe, 0x6c, 0x08, 0xb0, 0x20, 0xc7, 0xe9, 0x7d, 0x47, 0xd6, 0xcd, 0x3e, 0x23, 0x18, 0xad, 0x36,
	0xb2, 0x2c, 0xa5, 0x2a, 0x56, 0x64, 0xf6, 0x32, 0x27, 0x7c, 0x86, 0xf1, 0xdc, 0x4f, 0x0b, 0xdf,
	0xf4, 0xc4, 0x8f, 0xaf, 0x47, 0x35, 0xd7, 0x9c, 0x31, 0x3b, 0xc3, 0x27, 0x18, 0x2d, 0xc8, 0x05,
	0x26, 0x8b, 0xe3, 0xda, 0x75, 0x6c, 0x3d, 0x11, 0x7c, 0xed, 0x79, 0xe6, 0xfe, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x19, 0x50, 0x5b, 0x36, 0x66, 0x02, 0x00, 0x00,
}
